[project]
name = "a2a-streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.2",
    "httpx-sse>=0.4.0",
    "nest-asyncio>=1.6.0",
    "pydantic>=2.11.3",
    "streamlit>=1.44.1",
]
